<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <AvaloniaMinimumVersion>11.3.17</AvaloniaMinimumVersion>
    <AvaloniaVersion>12.0.2</AvaloniaVersion>
    <McpSdkVersion>1.2.0</McpSdkVersion>
  </PropertyGroup>
</Project>
